/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Paciente;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;

/**
 *
 * @author luise
 */
public class FrmPacientes extends javax.swing.JFrame {
    
    private Paciente.PacienteJDBC pacienteJDBC = new Paciente.PacienteJDBC();
    private int codigoPacienteSeleccionado = 0;
    /**
     * Creates new form FrmPacientes
     */
    public FrmPacientes() {
        initComponents();
        setLocationRelativeTo(null);
        cargarPacientes();
    }
    
    private void cargarPacientes() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Desactiva la edición directa en la tabla
            }
        };

        modelo.addColumn("Código");        // Columna 0
        modelo.addColumn("Nombre");        // Columna 1
        modelo.addColumn("Edad");          // Columna 2
        modelo.addColumn("Teléfono");      // Columna 3
        modelo.addColumn("Correo");        // Columna 4
        modelo.addColumn("Tipo Paciente"); // Columna 5
        modelo.addColumn("Estado");        // Columna 6

        try {
            // 2. Iterar sobre los datos traídos por PacienteJDBC
            for (Paciente paciente : pacienteJDBC.listarPacientes()) {
                modelo.addRow(new Object[]{
                    paciente.getCodigoPaciente(),
                    paciente.getNombreCompleto(),
                    paciente.getEdad(),
                    paciente.getTelefono(),
                    paciente.getCorreo(),
                    paciente.getTipoPaciente(),
                    paciente.getEstado()
                });
            }

            // 3. Aplicar el modelo recién construido a la JTable
            tblPacientes.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this, 
                    "Error al cargar pacientes: " + e.getMessage(), 
                    "Error JDBC", 
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbTipoPaciente = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        btonGuardar = new javax.swing.JButton();
        btonActualizar = new javax.swing.JButton();
        btonEliminar = new javax.swing.JButton();
        btonLimpiar = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();
        txtEdad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Módulo: Pacientes");

        jLabel6.setText("Nombre:");

        jLabel7.setText("Edad:");

        jLabel10.setText("Tipo de Pacientes:");

        cmbTipoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente", "Administrativo", "Visitante" }));

        jLabel8.setText("Telefono:");

        jLabel9.setText("Correo:");

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPacientes);

        btonGuardar.setText("Guardar");
        btonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonGuardarActionPerformed(evt);
            }
        });

        btonActualizar.setText("Modificar");
        btonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonActualizarActionPerformed(evt);
            }
        });

        btonEliminar.setText("Eliminar");
        btonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonEliminarActionPerformed(evt);
            }
        });

        btonLimpiar.setText("Limpiar");
        btonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonLimpiarActionPerformed(evt);
            }
        });

        btnVolverMenu.setText("Volver al Menú");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });

        jLabel11.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo)
                            .addComponent(txtNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEdad)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(29, 29, 29)
                                        .addComponent(cmbTipoPaciente, 0, 153, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(29, 29, 29)
                                        .addComponent(cmbEstado, 0, 211, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btonGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btonActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btonLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolverMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(cmbTipoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btonGuardar)
                    .addComponent(btonActualizar)
                    .addComponent(btonEliminar)
                    .addComponent(btonLimpiar)
                    .addComponent(btnVolverMenu))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacientesMouseClicked
        // TODO add your handling code here:
        int fila = tblPacientes.getSelectedRow();

        if (fila >= 0) {
            // Se guarda el código oculto o mostrado en la columna 0
            codigoPacienteSeleccionado = Integer.parseInt(
                    tblPacientes.getValueAt(fila, 0).toString()
            );

            // Se mapean los campos según las columnas asignadas en el modelo
            txtNombre.setText(tblPacientes.getValueAt(fila, 1).toString());
            txtEdad.setText(tblPacientes.getValueAt(fila, 2).toString());
            txtTelefono.setText(tblPacientes.getValueAt(fila, 3).toString());
            txtCorreo.setText(tblPacientes.getValueAt(fila, 4).toString());

            cmbTipoPaciente.setSelectedItem(
                    tblPacientes.getValueAt(fila, 5).toString()
            );

            cmbEstado.setSelectedItem(
                    tblPacientes.getValueAt(fila, 6).toString()
            );
        }
    }//GEN-LAST:event_tblPacientesMouseClicked

    private void btonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonGuardarActionPerformed
        // TODO add your handling code here:
        try {

            String nombre = txtNombre.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            String telefono = txtTelefono.getText();
            String correo = txtCorreo.getText();
            String tipoPaciente = cmbTipoPaciente.getSelectedItem().toString();
            String estado = cmbEstado.getSelectedItem().toString();

            Paciente paciente = new Paciente(
                    0,
                    nombre,
                    edad,
                    telefono,
                    correo,
                    tipoPaciente,
                    estado
            );

            Paciente.PacienteJDBC jdbc = new Paciente.PacienteJDBC();

            jdbc.insertarPaciente(paciente);

            JOptionPane.showMessageDialog(
                    this,
                    "Paciente registrado correctamente."
            );

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "La edad debe ser un número."
            );

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al guardar el paciente: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_btonGuardarActionPerformed

    private void btonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonActualizarActionPerformed
        // TODO add your handling code here:.     
        try {

            int fila = tblPacientes.getSelectedRow();

            if (fila == -1) {
                JOptionPane.showMessageDialog(
                        this,
                        "Seleccione un paciente de la tabla."
                );
                return;
            }

            int codigoPaciente = Integer.parseInt(
                    tblPacientes.getValueAt(fila, 0).toString()
            );

            String nuevoEstado = cmbEstado.getSelectedItem().toString();

            Paciente.PacienteJDBC jdbc = new Paciente.PacienteJDBC();

            jdbc.actualizarEstado(codigoPaciente, nuevoEstado);

            JOptionPane.showMessageDialog(
                    this,
                    "Estado del paciente actualizado correctamente."
            );

            cargarPacientes();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al actualizar el paciente: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_btonActualizarActionPerformed

    private void btonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonEliminarActionPerformed
        // TODO add your handling code here:
        try {

            int fila = tblPacientes.getSelectedRow();

            if (fila == -1) {
                JOptionPane.showMessageDialog(
                        this,
                        "Seleccione un paciente de la tabla."
                );
                return;
            }

            int codigoPaciente = Integer.parseInt(
                    tblPacientes.getValueAt(fila, 0).toString()
            );

            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro de eliminar este paciente?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmacion == JOptionPane.YES_OPTION) {

                Paciente.PacienteJDBC jdbc = new Paciente.PacienteJDBC();

                jdbc.eliminarPaciente(codigoPaciente);

                JOptionPane.showMessageDialog(
                        this,
                        "Paciente eliminado correctamente."
                );

                cargarPacientes();
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al eliminar el paciente: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_btonEliminarActionPerformed

    private void btonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonLimpiarActionPerformed
        // TODO add your handling code here:
        txtNombre.setText("");
        txtEdad.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");

        cmbTipoPaciente.setSelectedIndex(0);
        cmbEstado.setSelectedIndex(0);

        tblPacientes.clearSelection();
    }//GEN-LAST:event_btonLimpiarActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        // TODO add your handling code here:
        // Instanciar la ventana principal
        FrmPrincipal menuPrincipal = new FrmPrincipal();
        menuPrincipal.setVisible(true);
        menuPrincipal.setLocationRelativeTo(null); // Centrar en pantalla

        // Cerrar la ventana actual de citas
        this.dispose();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JButton btonActualizar;
    private javax.swing.JButton btonEliminar;
    private javax.swing.JButton btonGuardar;
    private javax.swing.JButton btonLimpiar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
